### PR TITLE
Fixed typo in class name

### PR DESCRIPTION
**Pull request by ZeroX-DG**
Hi! I love the idea behind this extension and I believe I spotted some typos in your code.

### CODE REVIEW

**Comment by huytd** [comment]
Cool, thank you for making the PR :D 

But the class name is intended tho, it reads "reading aid" -> "reaid". But yeah, it seems to be confusing.

Since the script will run in the context of any web page, a trivial class name might be conflicted with page's classes, so I'm trying to make it as unique as possible.

Since you're at it, would you mind update your PR a bit? I think `scrollreading-word` or something will be a good name (readable, still unique), what do you think?

**Comment by ZeroX-DG** [comment]
Yeah, `scrollreading-word` looks good to me. I'll update my PR.

**Comment by ZeroX-DG** [comment]
@huytd  PR updated!

**Comment by huytd** [comment]
Awesome!

**Comment by huytd** [comment]
Merged! Thank you so much! 🍺

**Pull request merged**
